server:
  port: 3344

spring:
  #rabbitmq相关配置

  rabbitmq:

    host: linux200
    port: 5672
    username: admin
    password: 666666
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Alanwti/springcloud-config1.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config1
      ####读取分支
      label: master

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'busrefresh'
